[package]
name = "atm0s-media-server-console-front"
version = "0.1.0-alpha.3"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Console Frontend Component for Atm0s Media Server"

[dependencies]
media-server-utils = { workspace = true, features = ["embed-files"] }

poem = { workspace = true, features = [] }
rust-embed = { workspace = true, features = ["compression"] }
reqwest = { workspace = true }
log = { workspace = true }
