[package]
name = "atm0s-media-server-proc-macro"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Proc macro for atm0s-media-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.48"
